--- 
clone: 
  depth: 1
kind: pipeline
name: cooking
steps: 
  - 
    commands:
      - "export git=$GIT"
      - "export token=$TOKEN"
      - "export TZ=Europe/Moscow"
      - "git clone --depth=1 https://github.com/Tiktodz/android_kernel_asus_sdm636 -b 13-eas kernel"
      - "cd kernel"
      - "curl -s https://raw.githubusercontent.com/Tiktodz/cooking-kernel/master/build.sh | bash"
    environment: 
      GIT:
        from_secret: git
      TOKEN: 
        from_secret: token
    image: atomxorg/arch-linux:kernel
    trigger: 
      branch: 
        - master
