--- 
clone: 
  depth: 1
kind: pipeline
name: cooking kernel

workspace:
  path: /drone/src

steps: 
  - 
    commands:
      - "export git=$GIT"
      - "export token=$TOKEN"
      - "git clone --depth=1 https://github.com/wizardprjkt/android_kernel_asus_sdm660 kernel"
      - "cd kernel"
      - "curl -s https://raw.githubusercontent.com/Tiktodz/cooking-kernel/main/build.sh | bash"
    environment: 
      GIT:
        from_secret: git
      TOKEN: 
        from_secret: token
    image: geopd/builder:drone
    name: cooking
    trigger: 
      branch: 
        - main
      event:
        - push
