version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
            git clone --depth=1 https://github.com/Tiktodz/Ruega-Kernel-X00T -b 9x13 kernel && cd kernel
            curl https://raw.githubusercontent.com/Tiktodz/cooking-kernel/circle/build.sh > run.sh
            source run.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
