version: 2.1
jobs:
  compile:
   docker:
      - image: wizardprjkt/dotkit:22.04
   steps:
      - run:
          command: |
            git clone --depth=1 https://github.com/Tiktodz/android_kernel_asus_sdm636 -b twelve-caf-eas kernel && cd kernel
            curl https://raw.githubusercontent.com/Tiktodz/cooking-kernel/circle/build.sh > run.sh
            source run.sh
          no_output_timeout : 6h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
